services:
  pre:
    build: .
    image: pre
    container_name: pre-app
    restart: always
    ports: 
      - 9001:9001
    volumes:
      - /export/data/logs/:/export/data/logs/
    environment:
      TZ: Asia/Shanghai