spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pre?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 123456
    type: org.apache.commons.dbcp2.BasicDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000s
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1s
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  pool:
    size: 8
    thread-name-prefix: task-scheduler-pool-
    await-termination-seconds: 60
    waitForTasksToComplete: true
  cache:
    redis:
      default-time-to-live: 86400

#日志
logging:
  file:
    max-history: 7
  level:
    root: debug
